### ISSUE TITLE
Create RPM package

### ISSUE THREAD

**Issue by turicas** [turicas/rows#120]
Create a RPM package and submit it to Fedora/RedHat/CentOS.

Some links could help:

- [How to create a RPM package](https://fedoraproject.org/wiki/How_to_create_an_RPM_package/es)
- [Package Review Process](https://fedoraproject.org/wiki/Package_Review_Process)
- [Join the package collection maintainers](https://fedoraproject.org/wiki/Join_the_package_collection_maintainers?rd=PackageMaintainers/Join)

**Comment by williamjmorenor** [comment]
rows is in Fedora

https://admin.fedoraproject.org/pkgdb/package/python-rows/

I can not build for epel (RedHat/CentOS) due a missing depency.

**Comment by turicas** [comment]
Nice, issue closed!

Thank you very much, @williamjmorenor! :D

Note: could you please add the information here when it can be built for epel?

**Comment by williamjmorenor** [comment]
I can not build rows in epel because it depend on unicodecsv and the maintainer of unicodecsv on have build it for Fedora 23 and Rawhide

https://bugzilla.redhat.com/show_bug.cgi?id=1279570

This library is maintained for a Redhatter and looks like than become a depency for a OpenStack tool so maybe it will be included in RHEL, but I can not build rows in epel until de maintainer or unicodecsv build it in epel or unicodecsv become part of RHEL it selft.
