### ISSUE TITLE
for branch python-3(rows support python3), still dependend on parquet , but parquet does not support python3, still cannot read parquet file in python3

### ISSUE THREAD

**Issue by redleaf2000** [turicas/rows#182]
for branch python-3(rows support python3), i download it , and follow the example here(http://blog.justen.eng.br/2016/03/reading-parquet-files-in-python-with-rows.html), to debug my code

and find the rows depend on  the thrift and parquet , but thrift and parquet are for python2, no version for python3.  and parquet seems to be generated by python-parquet: https://github.com/jcrobak/parquet-python (for parquet-python, it does not support python3 too)
is it right?

if i need to use rows on python3.5 to parse parquet files,  what is your suggestion to do it?
change thrift to python3?  change parquet to python3?   any other methods?

**Comment by turicas** [comment]
@redleaf2000, since python-parquet does not support Python3 (there's a discussion here: https://github.com/jcrobak/parquet-python/issues/15), I recommend you to:

- Use `rows`' Python2 version to convert the Parque file to another format (let's say, SQLite);
- Use the (future) version of rows on Python3 to read the SQLite file in yout application.

Since I can't solve this issue right now (it depends on python-parquet, and Parquet support is still experimental in rows), I'm closing it with the tag "wontfix".
Any other comments are welcome. :)

**Comment by turicas** [comment]
@redleaf2000, the python-parquet author just added support to Python 3 (but didn't release on PyPI yet). I'm also adding support for Python 3 on rows and already added the new version and made some changes: it worked! :smile: rows' parquet plugin now runs on both Python versions, but I'm still working on other Python 3 changes and didn't release this modification yet. Probably will release a new version in the next days.

More details on https://github.com/jcrobak/parquet-python/issues/15 and on the work-in-progress branch: https://github.com/turicas/rows/tree/feature/python3-support

**Comment by redleaf2000** [comment]
Thanks very much!
