### ISSUE TITLE
Problem detecting dialect

### ISSUE THREAD

**Issue by turicas** [turicas/rows#214]
@ramiroluz reported a problem reading a CSV file and I investigated the problem.

The Python's CSV sniffer autodetects and returns an impossible dialect in a specific case: when doublequotes are used into a CSV but the string containg it was not passed to the sniffer. When this happens it returns [an impossible dialect](https://docs.python.org/3/library/csv.html#csv.Dialect.doublequote) (`doublequote=False,escapechar=None`), so we need to force `doublequote=True` in this case.
It's a `csv`'s module bug, but we can fix it inside the `rows` library so our users won't have this problem (and can use the automatic dialect detection feature).

I did a little test, adding these lines just after the dialect detection on `import_from_csv`:

```python
    if not dialect.doublequote and dialect.escapechar is None:
        dialect.doublequote = True
```

and the file was read successfully.

**Comment by turicas** [comment]
@ramiroluz, I'm trying to reproduce this bug but I can't. Do you remember what CSV file you've used here? Could you please share it or create an way of reproducing this bug?

**Comment by ramiroluz** [comment]
I have sent you an email on February. Unfortunately I erased some emails with attachments recently, so I lost it.
But the problem was with an csv that have mixed styles of quotation. The first N lines, used by the library to detect the quotation doesn't had quoted strings, then in the next lines, quotes were used or vice-versa.
