### ISSUE TITLE
What do you think about making `_asdict` method public?

### ISSUE THREAD

**Issue by berinhard** [turicas/rows#336]
I'm using rows to parse a CSV, fetch some data from an API and create a new CSV. So, my code is:

```python
output_rows = []
for book in rows.import_from_csv(csv_path):
    isbn = get_isbn_from_title(book.title)
    row = book._asdict().copy()
    row['isbn_13'] = isbn
    output_rows.append(row)

# some code to use output_rows with a csv.DictWriter
```

I feel I'm violating something by calling `_asdict` internal method, but it's really useful for me since I'm using `rows.import_from_csv` to facilitate me from manipulating and adding data. What do you think about this? Is there a risk on exposing an `asdict` behavior the the `Row` object?

**Comment by turicas** [comment]
I'm not sure if this is really necessary (but I'm open to discuss), since:

- It's a [namedtuple](https://docs.python.org/3/library/collections.html#collections.namedtuple) and [`_asdict` is part of its API](https://docs.python.org/3/library/collections.html#collections.somenamedtuple._asdict) (even if it starts with underscore).
- There's an (old) issue to change the default row class: https://github.com/turicas/rows/issues/30 - if this is implemented you'd just pass `row_class=dict` in `import_from_csv` (the feature of changing the class is currently possible but with a little hack - please check [this comment](https://github.com/turicas/rows/issues/30#issuecomment-310565183)).

**Comment by berinhard** [comment]
Got it @turicas! I feel the suggestion in #30 covers this scenario I've described. So, after #30 being implemented, the following code snippet would work, right?

```python
output_rows = []
for book in rows.import_from_csv(csv_path, row_class=dict):
    isbn = get_isbn_from_title(book['title'])
    row = book.copy()
    row['isbn_13'] = isbn
    output_rows.append(row)
```

**Comment by berinhard** [comment]
Got it @turicas! I feel the suggestion in #30 covers this scenario I've described. So, after #30 being implemented, the following code snippet would work, right?

```python
output_rows = []
for book in rows.import_from_csv(csv_path, row_class=dict):
    isbn = get_isbn_from_title(book['title'])
    row = book.copy()
    row['isbn_13'] = isbn
    output_rows.append(row)
```

**Comment by turicas** [comment]
@berinhard yes! I've added this code snippet to #30's description as a suggested API.
