### ISSUE TITLE
Fix the columns in a CSV file

### ISSUE THREAD

**Issue by jeanferri** [turicas/rows#81]
Sometimes the CSV file is not well formed and may have one column (table header) not declared, raising an exception. In this case it may assumes the cell as empty.

For example:
> "column 1","column 2","column 4"
> 1,2,3,4
> a,b,c,d

Just a suggestion, it happened with us at Interlegis...

**Comment by turicas** [comment]
You can already do it -- it's just not well documented. ;-)
Please try something like this:

```python
field_names = ['first', 'second', 'third']
filename = 'myfile.csv'
table = rows.import_from_csv(filename, field_names=field_names, skip_header=False)
```
When you pass `field_names` (for *any* `import_from_*` function) it will overwrite the header read from the file. But if you also pass `skip_header=False` it'll consider the first line is actually a row instead of the header.

You can use this code and then export it to CSV so you'll have a nice formatted CSV with the header:

```python
rows.export_to_csv(table, 'myfile-fixed.csv')
# now remove the old one and be happy with this! ;)
```

You can read more about it in the [Common Parameters](https://github.com/turicas/rows#common-parameters) section inside [Importing Data](https://github.com/turicas/rows#importing-data).

> Note: these parameters names are not yet stable and may change in the future (but I'm not planning to remove this feature -- only the API may change).
